### ISSUE TITLE
Enhancement - Hyperlinks pointing to external URL's in the Tutorial should open in new browser tab

### ISSUE THREAD

**Issue by beAGoodQE** [muselab-d2x/d2x#10]
I'm progressing through the Tutorial and when I click on a hyperlink that points to something external like Github.com, for example:
 ([GitHub Actions Secrets for the repository or organization](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions)

I expect the page to open in a new tab, not on the current page I'm on.  This throws off my place in the tutorial.

**Comment by jonstahl** [comment]
I take your point and share your preference, but generally, we prefer to allow users to control where their hyperlinks open. (Also, markdown doesn't support this, which means it's somewhat of a pain to constantly drop back into HTML when writing.)

**Comment by beAGoodQE** [comment]
Sure, thanks for the explanation Jon, sounds good to me.
